language: objective-c

before_install:
  - gem install xcpretty

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Project/

script:
  - make clean test
