language: objective-c
osx_image: xcode8
before_install:
- gem install cocoapods

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
    #- make clean test
- pod lib lint --quick
