language: objective-c
osx_image: xcode8.2

install:
- gem install cocoapods
- gem install xcodeproj --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- ruby change_settings.rb

script:
- make clean test
- pod lib lint --quick
